logging:
  level:
    ROOT: info
mysql:
  username: root
  password: 123456
  schema: adm_videos
  url: localhost:${mysql.port}

# https://github.com/testcontainers/testcontainers-java/issues/4958
# Solucao do problema do WSL com Windows
# No caso foi para conectar em um host remoto